TF       := terraform -chdir=terraform
AGE_KEY  := $(HOME)/.config/sops/age/keys.txt

# Outside the repo (uncommittable) and outside $(AGE_KEY)'s dir (sops won't load it by accident).
CI_KEYS  := $(HOME)/hub-ci-keys

# Wraps every terraform command so credentials don't need sourcing separately.
TFENV     = sops exec-env terraform/secrets.enc.env

# `=` not `:=`: only evaluated (and only decrypts) by targets that need it.
HUB_IP    = $(shell $(TFENV) '$(TF) output -raw server_ipv4' 2>/dev/null)
SSH       = ssh deploy@$(HUB_IP)
ROOT_SSH  = ssh root@$(HUB_IP)

.PHONY: help secrets-init secrets-ci-init secrets init fmt validate plan apply destroy ip ssh sync platform up logs ps disk prune provision

help:
	@echo "First time only:"
	@echo "  make secrets-init  create your age key and .sops.yaml"
	@echo ""
	@echo "Infrastructure (rare):"
	@echo "  make init      terraform init"
	@echo "  make plan      terraform plan"
	@echo "  make apply     create/update the server, firewall and DNS"
	@echo ""
	@echo "Platform stacks (often):"
	@echo "  make up        sync stacks/ to the box and bring them up"
	@echo "  make sync      sync stacks/ only"
	@echo "  make ps        what is running"
	@echo "  make logs      tail traefik"
	@echo "  make disk      disk usage, and when cleanup last ran"
	@echo "  make prune     run the weekly cleanup now"
	@echo "  make provision apply ops/ (packages, systemd units) to the existing box"
	@echo "  make ssh       shell on the box"
	@echo ""
	@echo "Secrets:"
	@echo "  make secrets FILE=stacks/backup/secrets.enc.env   edit (or create) one secret"
	@echo "  make secrets-ci-init                              let CI decrypt projects/ secrets (once)"

# --------------------------------------------------------------------- secrets

# Your age keypair, at sops' default path — no flags needed on any sops command below.
# Back the private key up to your password manager; nothing else holds a copy.
# Refuses to overwrite an existing .sops.yaml (would silently drop the CI recipient
# that secrets-ci-init adds).
secrets-init:
	@set -e; \
	if [ -f .sops.yaml ]; then \
		echo ".sops.yaml already exists — nothing to do."; \
		echo "To rotate your key: edit .sops.yaml by hand, then 'sops updatekeys' every *.enc* file."; \
		exit 0; \
	fi; \
	if [ ! -f "$(AGE_KEY)" ]; then \
		mkdir -p "$$(dirname $(AGE_KEY))"; \
		age-keygen -o "$(AGE_KEY)"; \
		chmod 0600 "$(AGE_KEY)"; \
		echo "==> created $(AGE_KEY) — back this up to your password manager NOW"; \
	else \
		echo "==> $(AGE_KEY) already exists, reusing it"; \
	fi; \
	pub=$$(sed -n 's/^# public key: //p' "$(AGE_KEY)"); \
	test -n "$$pub" || { echo "no public key line in $(AGE_KEY)"; exit 1; }; \
	printf '%s\n' \
		'# Recipients for every encrypted file in this repo. Committed: public-key' \
		'# material. Generated by `make secrets-init`.' \
		'creation_rules:' \
		'  - path_regex: \.enc(\.env)?$$' \
		"    age: $$pub" > .sops.yaml; \
	echo "==> wrote .sops.yaml for $$pub"

# Adds a second age key that only CI holds, so the deploy workflow can decrypt a
# project's secrets and write /srv/<project>/.env itself.
#
# Scoped to projects/** — terraform's tokens and the restic password stay
# laptop-only. CI already has root-equivalent box access via HUB_SSH_KEY, so this
# grants nothing new there; it just avoids also handing over the accounts the box
# is built from.
#
# Private key lands at $(CI_KEYS)/ci_age.txt, 0600, for you to file away — not
# printed-and-shredded, since a terminal-only copy is unrecoverable the moment
# the window closes.
secrets-ci-init:
	@set -e; \
	test -f .sops.yaml || { echo "no .sops.yaml — run 'make secrets-init' first"; exit 1; }; \
	if grep -q '^  - path_regex: \^projects/' .sops.yaml; then \
		echo "CI rule already present in .sops.yaml — nothing to do."; \
		echo "To rotate the CI key: edit .sops.yaml by hand, then run"; \
		echo "'sops updatekeys' on every projects/*/secrets.enc.env."; \
		exit 0; \
	fi; \
	mine=$$(sed -n 's/^    age: //p' .sops.yaml | head -1); \
	test -n "$$mine" || { echo "could not read your recipient from .sops.yaml"; exit 1; }; \
	mkdir -p "$(CI_KEYS)"; chmod 0700 "$(CI_KEYS)"; \
	tmp="$(CI_KEYS)/ci_age.txt"; \
	test ! -e "$$tmp" || { echo "$$tmp already exists — file it and remove it before rerunning"; exit 1; }; \
	(umask 077; age-keygen -o "$$tmp" 2>/dev/null); \
	cipub=$$(sed -n 's/^# public key: //p' "$$tmp"); \
	test -n "$$cipub" || { echo "age-keygen produced no public key line"; exit 1; }; \
	printf '%s\n' \
		'# Recipients for every encrypted file in this repo. Committed: public-key material.' \
		'# First match wins — narrow project rule stays above the catch-all.' \
		'creation_rules:' \
		'  # Project secrets: you and CI, so deploy.yml can decrypt them onto the box.' \
		'  - path_regex: ^projects/.*\.enc(\.env)?$$' \
		'    age: >-' \
		"      $$mine," \
		"      $$cipub" \
		'  # Everything else (terraform, platform stacks) is laptop-only.' \
		'  - path_regex: \.enc(\.env)?$$' \
		"    age: $$mine" > .sops.yaml; \
	echo "==> rewrote .sops.yaml; CI recipient is $$cipub"; \
	for f in projects/*/secrets.enc.env projects/*/*.enc; do \
		[ -f "$$f" ] || continue; \
		sops updatekeys -y "$$f" && echo "==> re-encrypted $$f to both recipients"; \
	done; \
	echo ""; \
	echo "CI private key written to $$tmp (0600). It is not in git and not in"; \
	echo "your scrollback. Set it as the repo secret on every repo that deploys:"; \
	echo ""; \
	echo "  grep -v '^#' $$tmp | gh secret set SOPS_AGE_KEY --repo <owner>/<repo>"; \
	echo ""; \
	echo "Then save it to your password manager and delete the copy:"; \
	echo ""; \
	echo "  shred -u $$tmp"; \
	echo ""

# Opens $EDITOR on the decrypted content and re-encrypts on save; creates the file if new.
secrets:
	@test -n "$(FILE)" || { echo "usage: make secrets FILE=stacks/backup/secrets.enc.env"; exit 1; }
	@test -f .sops.yaml || { echo "no .sops.yaml — run 'make secrets-init' first"; exit 1; }
	sops $(FILE)


# ---------------------------------------------------------------- infrastructure

init:
	$(TFENV) '$(TF) init'

fmt:
	$(TF) fmt -recursive

validate:
	$(TF) validate

plan: validate
	$(TFENV) '$(TF) plan'

apply:
	$(TFENV) '$(TF) apply'

destroy:
	$(TFENV) '$(TF) destroy'

ip:
	@echo $(HUB_IP)

ssh:
	@$(SSH)

# -------------------------------------------------------------------- platform

# Decrypts to a throwaway staging copy on your laptop; the box never holds a key.
# `set -e` aborts before rsync on a bad decrypt. --delete only touches /srv/platform.
sync:
	@test -n "$(HUB_IP)" || { echo "no server_ipv4 output — run 'make apply' first"; exit 1; }
	@set -e; \
	stage=$$(mktemp -d); trap 'rm -rf "$$stage"' EXIT; \
	rsync -a --exclude '*.enc' --exclude '*.enc.env' --exclude '*.example' stacks/ "$$stage/"; \
	for src in stacks/*/secrets.enc.env stacks/*/*.enc; do \
		[ -f "$$src" ] || continue; \
		stack=$$(basename "$$(dirname "$$src")"); base=$$(basename "$$src"); \
		case "$$base" in \
			secrets.enc.env) out=".env" ;; \
			*)               out="$${base%.enc}" ;; \
		esac; \
		sops -d "$$src" > "$$stage/$$stack/$$out"; \
		chmod 0600 "$$stage/$$stack/$$out"; \
	done; \
	rsync -az --delete "$$stage/" deploy@$(HUB_IP):/srv/platform/

up: sync
	@$(SSH) 'set -e; for f in /srv/platform/*/compose.yml; do \
		echo "==> $$f"; docker compose -f "$$f" up -d --remove-orphans; \
	done'

platform: up

ps:
	@$(SSH) 'docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Image}}"'

logs:
	@$(SSH) 'docker logs -f --tail 100 platform-traefik-1'

# ----------------------------------------------------------------- housekeeping

# Weekly cleanup runs on its own via docker-prune.timer; these are for checking it.
disk:
	@$(SSH) 'df -h /; echo; docker system df; echo; \
		systemctl list-timers docker-prune.timer --no-pager'

prune:
	@$(SSH) '/usr/local/bin/docker-prune'

# ------------------------------------------------------------------ provisioning

# Changes to an *existing* box (packages, systemd units) without touching cloud-init.
# Runs as root, since `deploy` has no sudo. Idempotent.
provision:
	@test -n "$(HUB_IP)" || { echo "no server_ipv4 output — run 'make apply' first"; exit 1; }
	rsync -az ops/systemd/ root@$(HUB_IP):/etc/systemd/system/
	rsync -az ops/provision.sh root@$(HUB_IP):/root/provision.sh
	@$(ROOT_SSH) 'chmod +x /root/provision.sh && /root/provision.sh'
