TF       := terraform -chdir=terraform
AGE_KEY  := $(HOME)/.config/sops/age/keys.txt

# Where `secrets-ci-init` leaves the CI credentials for you to file. Deliberately
# outside the repo so it cannot be committed, and outside $(AGE_KEY)'s directory
# so sops never loads the CI key by accident when you run a local decrypt.
CI_KEYS  := $(HOME)/hub-ci-keys

# Every credential this repo needs — Hetzner, DigitalOcean, Spaces — lives in one
# encrypted file, so terraform commands are wrapped rather than requiring you to
# remember to `source` something first.
TFENV     = sops exec-env terraform/secrets.enc.env

# Lazily evaluated: `=` not `:=`, so terraform (and a sops decrypt) is only
# invoked by targets that actually need the address.
HUB_IP    = $(shell $(TFENV) '$(TF) output -raw server_ipv4' 2>/dev/null)
SSH       = ssh deploy@$(HUB_IP)
ROOT_SSH  = ssh root@$(HUB_IP)

.PHONY: help secrets-init secrets-ci-init secrets init fmt validate plan apply destroy ip ssh sync platform up logs ps disk prune provision

help:
	@echo "First time only:"
	@echo "  make secrets-init  create your age key and .sops.yaml"
	@echo ""
	@echo "Infrastructure (rare):"
	@echo "  make init      terraform init"
	@echo "  make plan      terraform plan"
	@echo "  make apply     create/update the server, firewall and DNS"
	@echo ""
	@echo "Platform stacks (often):"
	@echo "  make up        sync stacks/ to the box and bring them up"
	@echo "  make sync      sync stacks/ only"
	@echo "  make ps        what is running"
	@echo "  make logs      tail traefik"
	@echo "  make disk      disk usage, and when cleanup last ran"
	@echo "  make prune     run the weekly cleanup now"
	@echo "  make provision apply ops/ (packages, systemd units) to the existing box"
	@echo "  make ssh       shell on the box"
	@echo ""
	@echo "Secrets:"
	@echo "  make secrets FILE=stacks/backup/secrets.enc.env   edit (or create) one secret"
	@echo "  make secrets-ci-init                              let CI decrypt projects/ secrets (once)"

# --------------------------------------------------------------------- secrets

# One age keypair, yours, at the path sops looks in by default — so every other
# sops command in this file needs no flags, no --age, and no .sops.yaml editing.
# Back the private key up to your password manager: it is the only thing that can
# decrypt the *.enc* files committed here, and nothing else holds a copy.
#
# Refuses to overwrite an existing .sops.yaml. It is a one-time bootstrap, and
# `secrets-ci-init` adds a second recipient that a blind rewrite here would drop
# — silently, and only discovered when a deploy could no longer decrypt.
secrets-init:
	@set -e; \
	if [ -f .sops.yaml ]; then \
		echo ".sops.yaml already exists — nothing to do."; \
		echo "To rotate your key: edit .sops.yaml by hand, then 'sops updatekeys' every *.enc* file."; \
		exit 0; \
	fi; \
	if [ ! -f "$(AGE_KEY)" ]; then \
		mkdir -p "$$(dirname $(AGE_KEY))"; \
		age-keygen -o "$(AGE_KEY)"; \
		chmod 0600 "$(AGE_KEY)"; \
		echo "==> created $(AGE_KEY) — back this up to your password manager NOW"; \
	else \
		echo "==> $(AGE_KEY) already exists, reusing it"; \
	fi; \
	pub=$$(sed -n 's/^# public key: //p' "$(AGE_KEY)"); \
	test -n "$$pub" || { echo "no public key line in $(AGE_KEY)"; exit 1; }; \
	printf '%s\n' \
		'# Recipients for every encrypted file in this repo. Committed on purpose:' \
		'# it is public-key material, and having it here is what makes `sops <file>`' \
		'# work with no flags. Generated by `make secrets-init`.' \
		'creation_rules:' \
		'  - path_regex: \.enc(\.env)?$$' \
		"    age: $$pub" > .sops.yaml; \
	echo "==> wrote .sops.yaml for $$pub"

# Adds a second age key that only CI holds, so the deploy workflow can decrypt a
# project's own secrets and write /srv/<project>/.env itself. Without this a new
# project with secrets needs a manual out-of-band push, which is the one thing
# docs/new-project.md promises you never have to do.
#
# Scoped on purpose. CI can decrypt projects/** and nothing else: terraform's
# Hetzner and DigitalOcean tokens, and the restic password guarding every backup,
# stay laptop-only. That matters because CI already has HUB_SSH_KEY and `deploy`
# is root-equivalent via the docker group — so CI can already read any .env on
# the box. Letting it decrypt project secrets grants nothing new; letting it
# decrypt terraform/ would hand over the accounts the box is built from.
#
# The private key is written to $(CI_KEYS)/ci_age.txt, 0600, and left there for
# you to file in your password manager. It used to be printed to the terminal and
# shredded — which read as careful but meant the only copy lived in scrollback,
# and the key was unrecoverable the moment that window closed. A file you must
# delete on purpose is the safer default; the target tells you how.
secrets-ci-init:
	@set -e; \
	test -f .sops.yaml || { echo "no .sops.yaml — run 'make secrets-init' first"; exit 1; }; \
	if grep -q '^  - path_regex: \^projects/' .sops.yaml; then \
		echo "CI rule already present in .sops.yaml — nothing to do."; \
		echo "To rotate the CI key: edit both .sops.yaml files by hand, then"; \
		echo "'sops updatekeys' every projects/*/secrets.enc.env — see docs/studentbase-cutover.md."; \
		exit 0; \
	fi; \
	mine=$$(sed -n 's/^    age: //p' .sops.yaml | head -1); \
	test -n "$$mine" || { echo "could not read your recipient from .sops.yaml"; exit 1; }; \
	mkdir -p "$(CI_KEYS)"; chmod 0700 "$(CI_KEYS)"; \
	tmp="$(CI_KEYS)/ci_age.txt"; \
	test ! -e "$$tmp" || { echo "$$tmp already exists — file it and remove it before rerunning"; exit 1; }; \
	(umask 077; age-keygen -o "$$tmp" 2>/dev/null); \
	cipub=$$(sed -n 's/^# public key: //p' "$$tmp"); \
	test -n "$$cipub" || { echo "age-keygen produced no public key line"; exit 1; }; \
	printf '%s\n' \
		'# Recipients for every encrypted file in this repo. Committed on purpose:' \
		'# it is public-key material, and having it here is what makes `sops <file>`' \
		'# work with no flags.' \
		'#' \
		'# First match wins, so the narrow project rule must stay above the catch-all.' \
		'creation_rules:' \
		'  # Project secrets: yours and CI'"'"'s, so .github/workflows/deploy.yml can' \
		'  # decrypt them onto the box without a manual step.' \
		'  - path_regex: ^projects/.*\.enc(\.env)?$$' \
		'    age: >-' \
		"      $$mine," \
		"      $$cipub" \
		'  # Everything else — terraform, platform stacks — is laptop-only. CI has no' \
		'  # business with the Hetzner/DigitalOcean tokens or the restic password.' \
		'  - path_regex: \.enc(\.env)?$$' \
		"    age: $$mine" > .sops.yaml; \
	echo "==> rewrote .sops.yaml; CI recipient is $$cipub"; \
	for f in projects/*/secrets.enc.env projects/*/*.enc; do \
		[ -f "$$f" ] || continue; \
		sops updatekeys -y "$$f" && echo "==> re-encrypted $$f to both recipients"; \
	done; \
	echo ""; \
	echo "CI private key written to $$tmp (0600). It is not in git and not in"; \
	echo "your scrollback. Set it as the repo secret on every repo that deploys:"; \
	echo ""; \
	echo "  grep -v '^#' $$tmp | gh secret set SOPS_AGE_KEY --repo <owner>/<repo>"; \
	echo ""; \
	echo "Then save it to your password manager and delete the copy:"; \
	echo ""; \
	echo "  shred -u $$tmp"; \
	echo ""

# Opens $EDITOR on the decrypted content and re-encrypts on save; creates the file
# if it does not exist yet. No SSH, no key fetching — .sops.yaml says who the
# recipient is and sops finds your key at $(AGE_KEY).
secrets:
	@test -n "$(FILE)" || { echo "usage: make secrets FILE=stacks/backup/secrets.enc.env"; exit 1; }
	@test -f .sops.yaml || { echo "no .sops.yaml — run 'make secrets-init' first"; exit 1; }
	sops $(FILE)


# ---------------------------------------------------------------- infrastructure

init:
	$(TFENV) '$(TF) init'

fmt:
	$(TF) fmt -recursive

validate:
	$(TF) validate

plan: validate
	$(TFENV) '$(TF) plan'

apply:
	$(TFENV) '$(TF) apply'

destroy:
	$(TFENV) '$(TF) destroy'

ip:
	@echo $(HUB_IP)

ssh:
	@$(SSH)

# -------------------------------------------------------------------- platform

# Secrets are decrypted here, on your laptop, into a throwaway staging copy — the
# box never needs sops, an age key, or any way to decrypt anything. If a decrypt
# fails, `set -e` aborts before rsync runs, so a missing or unreadable secret can
# never reach the box as an empty file (or, with --delete, as a deletion).
#
# --delete so removing a stack locally removes it from the box. Only ever points
# at /srv/platform; project directories under /srv are owned by their own repos.
sync:
	@test -n "$(HUB_IP)" || { echo "no server_ipv4 output — run 'make apply' first"; exit 1; }
	@set -e; \
	stage=$$(mktemp -d); trap 'rm -rf "$$stage"' EXIT; \
	rsync -a --exclude '*.enc' --exclude '*.enc.env' --exclude '*.example' stacks/ "$$stage/"; \
	for src in stacks/*/secrets.enc.env stacks/*/*.enc; do \
		[ -f "$$src" ] || continue; \
		stack=$$(basename "$$(dirname "$$src")"); base=$$(basename "$$src"); \
		case "$$base" in \
			secrets.enc.env) out=".env" ;; \
			*)               out="$${base%.enc}" ;; \
		esac; \
		sops -d "$$src" > "$$stage/$$stack/$$out"; \
		chmod 0600 "$$stage/$$stack/$$out"; \
	done; \
	rsync -az --delete "$$stage/" deploy@$(HUB_IP):/srv/platform/

up: sync
	@$(SSH) 'set -e; for f in /srv/platform/*/compose.yml; do \
		echo "==> $$f"; docker compose -f "$$f" up -d --remove-orphans; \
	done'

platform: up

ps:
	@$(SSH) 'docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Image}}"'

logs:
	@$(SSH) 'docker logs -f --tail 100 platform-traefik-1'

# ----------------------------------------------------------------- housekeeping

# Cleanup runs weekly on its own (docker-prune.timer, installed by cloud-init).
# These are for looking at it, and for the day a deploy fills the disk early.
disk:
	@$(SSH) 'df -h /; echo; docker system df; echo; \
		systemctl list-timers docker-prune.timer --no-pager'

prune:
	@$(SSH) '/usr/local/bin/docker-prune'

# ------------------------------------------------------------------ provisioning

# For changes to an *existing* box: packages, systemd units. Never touches
# cloud-init.yml/user_data, so it never forces a server rebuild. `deploy` has no
# sudo by design, so this runs as root over the same key Terraform provisions.
# Idempotent — safe to re-run any time ops/ changes.
provision:
	@test -n "$(HUB_IP)" || { echo "no server_ipv4 output — run 'make apply' first"; exit 1; }
	rsync -az ops/systemd/ root@$(HUB_IP):/etc/systemd/system/
	rsync -az ops/provision.sh root@$(HUB_IP):/root/provision.sh
	@$(ROOT_SSH) 'chmod +x /root/provision.sh && /root/provision.sh'
