TF       := terraform -chdir=terraform
AGE_KEY  := $(HOME)/.config/sops/age/keys.txt

# Every credential this repo needs — Hetzner, DigitalOcean, Spaces — lives in one
# encrypted file, so terraform commands are wrapped rather than requiring you to
# remember to `source` something first.
TFENV     = sops exec-env terraform/secrets.enc.env

# Lazily evaluated: `=` not `:=`, so terraform (and a sops decrypt) is only
# invoked by targets that actually need the address.
HUB_IP    = $(shell $(TFENV) '$(TF) output -raw server_ipv4' 2>/dev/null)
SSH       = ssh deploy@$(HUB_IP)
ROOT_SSH  = ssh root@$(HUB_IP)

.PHONY: help secrets-init secrets init fmt validate plan apply destroy ip ssh sync platform up logs ps disk prune provision

help:
	@echo "First time only:"
	@echo "  make secrets-init  create your age key and .sops.yaml"
	@echo ""
	@echo "Infrastructure (rare):"
	@echo "  make init      terraform init"
	@echo "  make plan      terraform plan"
	@echo "  make apply     create/update the server, firewall and DNS"
	@echo ""
	@echo "Platform stacks (often):"
	@echo "  make up        sync stacks/ to the box and bring them up"
	@echo "  make sync      sync stacks/ only"
	@echo "  make ps        what is running"
	@echo "  make logs      tail traefik"
	@echo "  make disk      disk usage, and when cleanup last ran"
	@echo "  make prune     run the weekly cleanup now"
	@echo "  make provision apply ops/ (packages, systemd units) to the existing box"
	@echo "  make ssh       shell on the box"
	@echo ""
	@echo "Secrets:"
	@echo "  make secrets FILE=stacks/backup/secrets.enc.env   edit (or create) one secret"

# --------------------------------------------------------------------- secrets

# One age keypair, yours, at the path sops looks in by default — so every other
# sops command in this file needs no flags, no --age, and no .sops.yaml editing.
# Back the private key up to your password manager: it is the only thing that can
# decrypt the *.enc* files committed here, and nothing else holds a copy.
secrets-init:
	@set -e; \
	if [ ! -f "$(AGE_KEY)" ]; then \
		mkdir -p "$$(dirname $(AGE_KEY))"; \
		age-keygen -o "$(AGE_KEY)"; \
		chmod 0600 "$(AGE_KEY)"; \
		echo "==> created $(AGE_KEY) — back this up to your password manager NOW"; \
	else \
		echo "==> $(AGE_KEY) already exists, reusing it"; \
	fi; \
	pub=$$(sed -n 's/^# public key: //p' "$(AGE_KEY)"); \
	test -n "$$pub" || { echo "no public key line in $(AGE_KEY)"; exit 1; }; \
	printf '%s\n' \
		'# Recipients for every encrypted file in this repo. Committed on purpose:' \
		'# it is public-key material, and having it here is what makes `sops <file>`' \
		'# work with no flags. Generated by `make secrets-init`.' \
		'creation_rules:' \
		'  - path_regex: \.enc(\.env)?$$' \
		"    age: $$pub" > .sops.yaml; \
	echo "==> wrote .sops.yaml for $$pub"

# Opens $EDITOR on the decrypted content and re-encrypts on save; creates the file
# if it does not exist yet. No SSH, no key fetching — .sops.yaml says who the
# recipient is and sops finds your key at $(AGE_KEY).
secrets:
	@test -n "$(FILE)" || { echo "usage: make secrets FILE=stacks/backup/secrets.enc.env"; exit 1; }
	@test -f .sops.yaml || { echo "no .sops.yaml — run 'make secrets-init' first"; exit 1; }
	sops $(FILE)

# ---------------------------------------------------------------- infrastructure

init:
	$(TFENV) '$(TF) init'

fmt:
	$(TF) fmt -recursive

validate:
	$(TF) validate

plan: validate
	$(TFENV) '$(TF) plan'

apply:
	$(TFENV) '$(TF) apply'

destroy:
	$(TFENV) '$(TF) destroy'

ip:
	@echo $(HUB_IP)

ssh:
	@$(SSH)

# -------------------------------------------------------------------- platform

# Secrets are decrypted here, on your laptop, into a throwaway staging copy — the
# box never needs sops, an age key, or any way to decrypt anything. If a decrypt
# fails, `set -e` aborts before rsync runs, so a missing or unreadable secret can
# never reach the box as an empty file (or, with --delete, as a deletion).
#
# --delete so removing a stack locally removes it from the box. Only ever points
# at /srv/platform; project directories under /srv are owned by their own repos.
sync:
	@test -n "$(HUB_IP)" || { echo "no server_ipv4 output — run 'make apply' first"; exit 1; }
	@set -e; \
	stage=$$(mktemp -d); trap 'rm -rf "$$stage"' EXIT; \
	rsync -a --exclude '*.enc' --exclude '*.enc.env' --exclude '*.example' stacks/ "$$stage/"; \
	sops -d stacks/traefik/admin-users.enc > "$$stage/traefik/admin-users"; \
	sops -d stacks/backup/secrets.enc.env  > "$$stage/backup/.env"; \
	chmod 0600 "$$stage/traefik/admin-users" "$$stage/backup/.env"; \
	rsync -az --delete "$$stage/" deploy@$(HUB_IP):/srv/platform/

up: sync
	@$(SSH) 'set -e; for f in /srv/platform/*/compose.yml; do \
		echo "==> $$f"; docker compose -f "$$f" up -d --remove-orphans; \
	done'

platform: up

ps:
	@$(SSH) 'docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Image}}"'

logs:
	@$(SSH) 'docker logs -f --tail 100 platform-traefik-1'

# ----------------------------------------------------------------- housekeeping

# Cleanup runs weekly on its own (docker-prune.timer, installed by cloud-init).
# These are for looking at it, and for the day a deploy fills the disk early.
disk:
	@$(SSH) 'df -h /; echo; docker system df; echo; \
		systemctl list-timers docker-prune.timer --no-pager'

prune:
	@$(SSH) '/usr/local/bin/docker-prune'

# ------------------------------------------------------------------ provisioning

# For changes to an *existing* box: packages, systemd units. Never touches
# cloud-init.yml/user_data, so it never forces a server rebuild. `deploy` has no
# sudo by design, so this runs as root over the same key Terraform provisions.
# Idempotent — safe to re-run any time ops/ changes.
provision:
	@test -n "$(HUB_IP)" || { echo "no server_ipv4 output — run 'make apply' first"; exit 1; }
	rsync -az ops/systemd/ root@$(HUB_IP):/etc/systemd/system/
	rsync -az ops/provision.sh root@$(HUB_IP):/root/provision.sh
	@$(ROOT_SSH) 'chmod +x /root/provision.sh && /root/provision.sh'
