name: dozzle

services:
  dozzle:
    image: amir20/dozzle:v8
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`logs.waqasali.dev`)
      - traefik.http.routers.dozzle.tls.certresolver=le
      - traefik.http.routers.dozzle.middlewares=admin-auth@file
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
    networks:
      - edge
    mem_limit: 64m
    security_opt:
      - no-new-privileges:true

networks:
  edge:
    external: true
